name: flutter_statusbarcolor_ns
description: A package can help you to change your flutter app's statusbar's color or navigationbar's color programmatically.
version: 0.6.0
homepage: https://github.com/Sameerkash/flutter_statusbarcolor

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sameer.flutterstatusbarcolor.flutterstatusbarcolor
        pluginClass: FlutterStatusbarcolorPlugin
      ios:
        pluginClass: FlutterStatusbarcolorPlugin

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.10.0"

